/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in real projects.
// It is included here so TypeScript understands Next.js types from the start.
